---
title: "R Notebook"
output: html_notebook
---

```{r}
#### Load necessary packages and data ####
library(tidyverse)
library(RColorBrewer)
```


```{r}
#### Load necessary packages and data ####
library(tidyverse)
library(shiny)
library(networkD3)

datadir <- "/data/DataFest2018"
MAX <- 0.99
CURRENCY_CAD2USD = 0.78
CURRENCY_EUR2USD = 1.23
##########################
# READ In data

## sub dataset
#data_input <- read_csv(file.path(datadir, "subset2.csv"))
data_input <- read_csv(file.path(datadir, "subset1.csv"))
#data_input <- data_input[,-1]


## CAUTION: full dataset
#data_input <- read_csv(file.path(datadir, "datafest2018.csv"))

##########################
tmp <- data_input

# deal with Currency
tmp <- tmp %>% 
    mutate(
        estimatedSalary = 
            ifelse(is.na(salaryCurrency), estimatedSalary,
                ifelse(
                    salaryCurrency == "EUR", 
                    estimatedSalary * CURRENCY_EUR2USD, 
                    estimatedSalary))) %>% 
    mutate(
        estimatedSalary = 
            ifelse(is.na(salaryCurrency), estimatedSalary,
                ifelse(
                    salaryCurrency == "CAD", 
                    estimatedSalary * CURRENCY_CAD2USD, 
                    estimatedSalary)))
    
data_salary2US <- tmp

##########################
subdata <- data_salary2US  %>% 
    #filter(salaryCurrency == "USD") %>%
    select(normTitle, #normTitleCategory, 
         educationRequirement, 
         experienceRequired, 
         supervisingJob, 
         estimatedSalary, 
         licenseRequiredJob) %>%
    na.omit

##########################
tmp <- subdata

# deal with education
x <- c(0, 1, 2, 0, 1, 2)
y <- c(0, 1, 2, "None", "High school", "Higher education")
tmp$educationRequirement <- x[match(tmp$educationRequirement, y)]

# summarizing the job
tmp <- tmp %>% 
    filter(normTitle != "") %>%
    group_by(normTitle) %>% 
    summarise(
        educationRequirement = mean(educationRequirement), 
        experienceRequired   = mean(experienceRequired), 
        supervisingJob       = mean(supervisingJob), 
        licenseRequiredJob   = mean(licenseRequiredJob),
        estimatedSalary      = mean(estimatedSalary))
dat_job <- tmp %>%  as.data.frame

###############

tmp <- dat_job
rownames(tmp) <- tmp$normTitle

tmp <- tmp %>%
    select(-normTitle) %>% #, -normTitleCategory) %>% 
    as.matrix

dst <- as.matrix(dist(scale(tmp)))
sim <- 1 / (1 + dst)
adj <- sim - diag(1, dim(sim))
```

node features
```{r}
tmp<- data_input %>% 
    group_by(normTitle) %>% 
    summarise(
        mean_click  = median(clicks, na.rm = TRUE),
        mean_salary = median(estimatedSalary, na.rm = TRUE))

pal = brewer.pal(9, "Reds")
col = colorRampPalette(pal)
        
#This adds a column of color values
# based on the salary values
tmp$col_idx    <- as.numeric(cut(tmp$mean_salary, breaks = 10))
tmp$col_salary <- col(100)[tmp$col_idx]

tmp1 <- left_join(dat_job, tmp, by = "normTitle")
tmp2 <- data.frame(
            normTitle  = colnames(adj),
            group = 1)
dat_features <- left_join(tmp1, tmp2, by = "normTitle")
```



```{r}
save(dat_features, dat_job, adj, 
     file=file.path(datadir, "dat_job_adjMatrix_fulldata.RData"))
```

```{r}
save(dat_features, dat_job, adj, 
     file=file.path(datadir, "dat_job_adjMatrix_subset1.RData"))
```

```{r}
save(dat_features, dat_job, adj, 
     file=file.path(datadir, "dat_job_adjMatrix_subset2.RData"))

#write_csv(dat_job, file.path(datadir, "data_job_subset2.csv"))
#write_csv(adj,     file.path(datadir, "adj_matrix_subset2.csv"))
```

```{r}
datadir <- "/data/DataFest2018"
load(file.path(datadir, "dat_job_adjMatrix_subset2.RData"))
```

```{r}
datadir <- "/data/DataFest2018"
load(file.path(datadir, "dat_job_adjMatrix_fulldata.RData"))
```
